name: 'Branch Block Action'
description: "Blocks access of a branch to specific entities"
author: 'EquityBee'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  branch-name:
    required: true
    description: 'The name of the branch to which access will be restricted'
  users:
    required: true
    description: 'List of users to restrict access to. Empty list will restrict it to everyone'
  teams:
    required: true
    description: 'List of teams to restrict access to. Empty list will restrict it to everyone'
  apps:
    required: true
    description: 'List of apps to restrict access to. Empty list will restrict it to everyone'
runs:
  using: 'node12'
  main: 'dist/index.js'
